version: '3.8'

# Simple test configuration for Docker setup
services:
  # Test the application build
  app-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: fact-checker-test
    ports:
      - "8080:8000"
    environment:
      - ENVIRONMENT=development
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5432
      - DATABASE_NAME=fact_checker_test
      - DATABASE_USER=test
      - DATABASE_PASSWORD=test
      - REDIS_URL=redis://localhost:6379/0
    volumes:
      - .:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge
