apiVersion: apps/v1
kind: Deployment
metadata:
  name: fact-checker-api
  namespace: fact-checker
  labels:
    app: fact-checker-api
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fact-checker-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: fact-checker-api
        version: v1
    spec:
      imagePullSecrets:
      - name: docker-registry-secret
      containers:
      - name: api
        image: fact-checker-api:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        # Configuration from ConfigMap
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: fact-checker-config
              key: ENVIRONMENT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: fact-checker-config
              key: LOG_LEVEL
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              name: fact-checker-config
              key: API_HOST
        - name: API_PORT
          valueFrom:
            configMapKeyRef:
              name: fact-checker-config
              key: API_PORT
        
        # Database Configuration
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: fact-checker-config
              key: DATABASE_URL
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fact-checker-secrets
              key: DATABASE_PASSWORD
        
        # Redis Configuration
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: fact-checker-config
              key: REDIS_URL
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: REDIS_PASSWORD
        
        # API Keys
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: fact-checker-secrets
              key: SECRET_KEY
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: fact-checker-secrets
              key: OPENAI_API_KEY
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: fact-checker-secrets
              key: ANTHROPIC_API_KEY
        - name: MISTRAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: fact-checker-secrets
              key: MISTRAL_API_KEY
        
        # External Services
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: fact-checker-secrets
              key: SENDGRID_API_KEY
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: fact-checker-secrets
              key: STRIPE_SECRET_KEY
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: fact-checker-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: fact-checker-secrets
              key: AWS_SECRET_ACCESS_KEY
        
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        
        # Security Context
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        
        # Volume Mounts
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: cache-volume
          mountPath: /app/cache
      
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: cache-volume
        emptyDir: {}
      
      # Security Context for Pod
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      
      # Node Selection
      nodeSelector:
        kubernetes.io/arch: amd64
      
      # Tolerations and Affinity
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - fact-checker-api
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: fact-checker-api
  namespace: fact-checker
  labels:
    app: fact-checker-api
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: fact-checker-api
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fact-checker-api-hpa
  namespace: fact-checker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fact-checker-api
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
