apiVersion: apps/v1
kind: Deployment
metadata:
  name: fact-checker-app
  namespace: fact-checker
  labels:
    app: dspy-fact-checker
    component: app
    version: v1.0.0
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: dspy-fact-checker
      component: app
  template:
    metadata:
      labels:
        app: dspy-fact-checker
        component: app
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: fact-checker-service-account
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: app
        image: fact-checker:latest  # Replace with your actual image
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: fact-checker-config
              key: ENVIRONMENT
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: fact-checker-config
              key: APP_NAME
        - name: VERSION
          valueFrom:
            configMapKeyRef:
              name: fact-checker-config
              key: VERSION
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: fact-checker-config
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: fact-checker-config
              key: DATABASE_PORT
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: fact-checker-config
              key: DATABASE_NAME
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: fact-checker-secrets
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fact-checker-secrets
              key: DATABASE_PASSWORD
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: fact-checker-config
              key: REDIS_URL
        - name: CELERY_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: fact-checker-config
              key: CELERY_BROKER_URL
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            configMapKeyRef:
              name: fact-checker-config
              key: CELERY_RESULT_BACKEND
        - name: QDRANT_URL
          valueFrom:
            configMapKeyRef:
              name: fact-checker-config
              key: QDRANT_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: fact-checker-secrets
              key: SECRET_KEY
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: fact-checker-secrets
              key: ANTHROPIC_API_KEY
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: fact-checker-secrets
              key: OPENAI_API_KEY
        volumeMounts:
        - name: app-logs
          mountPath: /app/logs
        - name: app-uploads
          mountPath: /app/uploads
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2
            memory: 4Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: app-logs
        persistentVolumeClaim:
          claimName: app-logs-pvc
      - name: app-uploads
        persistentVolumeClaim:
          claimName: app-uploads-pvc
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: fact-checker
  labels:
    app: dspy-fact-checker
    component: app
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: dspy-fact-checker
    component: app

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fact-checker-app-hpa
  namespace: fact-checker
  labels:
    app: dspy-fact-checker
    component: app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fact-checker-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fact-checker-app-pdb
  namespace: fact-checker
  labels:
    app: dspy-fact-checker
    component: app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: dspy-fact-checker
      component: app

---
# Service Account for the application
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fact-checker-service-account
  namespace: fact-checker
  labels:
    app: dspy-fact-checker

---
# Role for the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fact-checker-role
  namespace: fact-checker
  labels:
    app: dspy-fact-checker
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]

---
# Role binding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fact-checker-role-binding
  namespace: fact-checker
  labels:
    app: dspy-fact-checker
subjects:
- kind: ServiceAccount
  name: fact-checker-service-account
  namespace: fact-checker
roleRef:
  kind: Role
  name: fact-checker-role
  apiGroup: rbac.authorization.k8s.io
